{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-contour" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  secretName: {{ printf "%s-contour-crt" (include "common.names.fullname" .) }}
  commonName: "contour"
  dnsNames:
    - "contour"
    - "contour.{{ include "common.names.namespace" . }}"
    - "contour.{{ include "common.names.namespace" . }}.svc"
    - "contour.{{ include "common.names.namespace" . }}.svc.cluster.local"
  issuerRef:
    name: {{ include "common.names.fullname" . | quote }}
    kind: Issuer
{{- end }}
